# Travis-CI file for Espruino

language: c
python:
  - "3.6"
# Ensure we clone the last 1000 commits, which allows us to get the commit counter correct!
git:
  depth: 1000

before_script:
 - python --version
 - source ./scripts/provision.sh $BOARD

after_script:
  - "if [[ -n \"$UPLOADTOKEN\" ]]; then
       ls *.bin *.hex *.tgz *.zip | xargs -I {} curl -v -F \"binary=@{}\" \"http://www.espruino.com/travis_upload.php?commit=$TRAVIS_COMMIT&branch=$TRAVIS_BRANCH&token=$UPLOADTOKEN\";
     fi"

compiler:
  - gcc

env:
  global:
    - TRAVIS=1
    - V=0
    - RELEASE=1
  matrix:
    - BOARD=LINUX
    - BOARD=ESPRUINOBOARD PAD_FOR_BOOTLOADER=1
    - BOARD=PICO_R1_3 PAD_FOR_BOOTLOADER=1
    - BOARD=ESPRUINOWIFI PAD_FOR_BOOTLOADER=1
    - BOARD=PUCKJS DFU_UPDATE_BUILD=1
    - BOARD=PIXLJS DFU_UPDATE_BUILD=1
    - BOARD=MDBT42Q DFU_UPDATE_BUILD=1
    - BOARD=BANGLEJS DFU_UPDATE_BUILD=1
    - BOARD=BANGLEJS2 DFU_UPDATE_BUILD=1
    - BOARD=ESP32
    - BOARD=ESP8266_BOARD
    - BOARD=ESP8266_4MB
    - BOARD=MICROBIT2
    - BOARD=SMARTIBOT DFU_UPDATE_BUILD=1
    - BOARD=RAK5010
    - BOARD=PUCKJS_MINIMAL DFU_UPDATE_BUILD=1

script: make

notifications:
  email: false
